<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.1</Version>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ForceDesignerDPIUnaware>true</ForceDesignerDPIUnaware>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BHelper</AssemblyName>
    <RootNamespace>BHelper</RootNamespace>
    <ApplicationIcon>Resources\gcc.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Resources\gcc.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Include="Resources\gauge_left_32.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Resources\gauge_balanced_32.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Resources\gauge_up_32.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Resources\gauge_right_32.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Resources\cross-23.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Resources\readiness_score_32dp_fill.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.8" />
    <PackageReference Include="System.Management" Version="10.0.2" />
  </ItemGroup>

</Project>
